### ISSUE TITLE
crash on aarch64 in simd optimisation

### ISSUE THREAD

**Issue by nullr0ute** [libjpeg-turbo/libjpeg-turbo#97]
We're seeing the following crash with 1.5.0 on aarch64 (Fedora 25)

Full details in this downstream bug: https://bugzilla.redhat.com/show_bug.cgi?id=1368569

Backtrace:
Thread 1 "Xvnc" received signal SIGSEGV, Segmentation fault.
encode_mcu_huff (cinfo=0x2aaee610850, MCU_data=<optimized out>) at jchuff.c:675
675          state.cur.last_dc_val[ci] = MCU_data[blkn][0][0];
(gdb) bt full
#0  encode_mcu_huff (cinfo=0x2aaee610850, MCU_data=<optimized out>)
    at jchuff.c:675
        entropy = 0x2aaee9eda90
        state = {next_output_byte = 0x2aaee748142 "\001\377",
          free_in_buffer = 125054, cur = {put_buffer = 13396343463626488332,
            put_bits = 16, last_dc_val = {210, -5, -1, 15132390}},
          cinfo = 0x2aaee610850}
        blkn = 3
        ci = -1487503252
        compptr = <optimized out>

**Comment by dcommander** [comment]
Test the code in GitHub master.  I believe this issue is already fixed.

**Comment by nullr0ute** [comment]
Do you know which commit?

**Comment by dcommander** [comment]
1120ff29a178ee666504f0067e7c079a6b792296

**Comment by nullr0ute** [comment]
So with that patch plus then trying with 9055fb4 too we're still seeing a crash, nothing else in the commits since 1.5.0 seemed relevant.

Using host libthread_db library "/lib64/libthread_db.so.1".
0x000003ff9a86ad84 in __GI___select (nfds=512, readfds=0x2aabaeb4628 <maxBigRequestSize>, writefds=0x2aabadbd980 <Dispatch+184>, writefds@entry=0x0, exceptfds=0x3ffdba6fab0, exceptfds@entry=0x0, timeout=0x3ffdba6f818)
    at ../sysdeps/unix/sysv/linux/generic/select.c:45
45        result = SYSCALL_CANCEL (pselect6, nfds, readfds, writefds, exceptfds, tsp,
(gdb) continue
Continuing.
 
Thread 1 "Xvnc" received signal SIGSEGV, Segmentation fault.
encode_mcu_huff (cinfo=0x2aae7f40950, MCU_data=<optimized out>) at jchuff.c:675
675           state.cur.last_dc_val[ci] = MCU_data[blkn][0][0];
(gdb) bt full
#0  encode_mcu_huff (cinfo=0x2aae7f40950, MCU_data=<optimized out>) at jchuff.c:675
        entropy = 0x2aae830ab80
        state = {next_output_byte = 0x2aae803f65a "hߑ\341U\253Y\316\\\221oW\370\066z\257\374%^;\377", free_in_buffer = 125702, cur = {put_buffer = 7713560057402476410, put_bits = 33, last_dc_val = {-306, 58, -21, 906589833}},
          cinfo = 0x2aae7f40950}
        blkn = 1
        ci = -1692630564
        compptr = <optimized out>

**Comment by dcommander** [comment]
Several things to try that will give me much-needed data points:

* Try setting the environment variable `JSIMD_NOHUFFENC=1` to disable the SIMD-accelerated Huffman encoder at run time.  If the crash goes away, then that tells me that the problem is in the 64-bit NEON Huffman encoding algorithm, which is new in libjpeg-turbo 1.5.

* Try setting the environment variable `JSIMD_FORCENONE=1` to disable all of the SIMD code in libjpeg-turbo at run time.  If the crash goes away, then that tells me that the problem is in some other 64-bit NEON algorithm.

* Try building TigerVNC against plain libjpeg.  If the crash goes away, then that tells me that the problem is in one of the libjpeg-turbo C algorithms (I somewhat doubt that this is the case, but I've been surprised before.)

I unfortunately don't have access to a machine on which I could install Fedora 25 aarch64.  My only aarch64 test platforms are a jailbroken iPhone 5S and a Google Nexus 5X

**Comment by nullr0ute** [comment]
So 1.4.x worked fine on aarch64 in the Fedora 24 time frame.

For the NEON implementation do you happen to know if it uses the same code for ARMv7 as ARMv8?

**Comment by dcommander** [comment]
No, the ARMv7 and ARMv8 NEON implementations are structurally similar, but they don't share any code.

**Comment by dcommander** [comment]
The fact that this worked under F24 and libjpeg-turbo 1.4.x would be meaningful only if the TigerVNC code you were using on that platform was identical to the TigerVNC code you're using now.  Otherwise, there's no way of knowing whether the bug was introduced by the libjpeg-turbo upgrade or the TigerVNC upgrade.  That's why I need the aforementioned data points.  libjpeg-turbo 1.5 introduced 64-bit NEON-accelerated Huffman encoding, but it also introduced 64-bit NEON-accelerated implementations of most of the other compression algorithms, so the bug could easily be in one of those.

**Comment by nullr0ute** [comment]
So problem goes away with JSIMD_NOHUFFENC=1

**Comment by dcommander** [comment]
OK,  @mayeut, seems like there may be a bug in the ARM64 Huffman encoder.

**Comment by mayeut** [comment]
I started a docker image of Fedora 25 image running aarch64 (through qemu, see https://hub.docker.com/r/multiarch/qemu-user-static/)
I compiled from sources & ran the tests (I tested both SIMD paths for huffman encoding):
`make test tjtest`
No errors.
After `dnf install libjpeg-turbo`, I ran part of those tests again (useless to run tjtest here):
`LD_PRELOAD=/usr/lib64/libjpeg.so.62 make test`
There were no errors.

@nullr0ute, 
It would be good to get a test case (I don't know how to start a vncserver on this image to try & reproduce, I'm still trying to get this running though).
It might also be good to know if those tests are passing on your setup.

**Comment by nullr0ute** [comment]
All the builds for <= F-25 are here (F-26 was merged into primary instance for F-26 recently) with full build/check logs:
http://arm.koji.fedoraproject.org/koji/packageinfo?packageID=10414

Latest F-25 build (with the initial SIMD fix referenced above) is and all the tests pass:
http://arm.koji.fedoraproject.org/koji/buildinfo?buildID=402274

All tests pass. The current reproducer that we have is vncserver.

**Comment by mayeut** [comment]
I've been able to reproduce the issue running `Xvnc` from the `tigervnc-server` package.
As of now I can't pinpoint the origin of the problem. I've been able to dump the data fed to `libjpeg-turbo` which purpose was to create a minimal test case but, unfortunately, when using this data with a small executable that mimics `tigervnc` usage of `libjpeg`, no crash occurs.
I checked that the assembly function properly save/restore registers that are callee-saved (only `x19` & `x20` in this case, unless I'm missing something in this ABI.) & that the stack is properly handled.
I can't work with `gdb` which doesn't help (I will have to figure that out how to use `qemu` gdb stub in this environment)
As I can only investigate this on my spare/free time, resolution might be slow.

**Comment by mayeut** [comment]
Seems my statement regarding properly saving/restoring callee-saved registered was only true until something "weird" occurred in the middle of the function (probably a context switch that also lead to an address space switch or something else that "messed up" the stack - rightfully)...
The aarch64 ABI states:
> A process may only access (for reading or writing) the closed interval of the entire stack delimited by [SP, stack-base – 1].

The function does not conform to this statement.
It would be great if someone could confirm my guess. Testing does confirm it for now.

It's not the only function that suffers from this problem, here's the full list:
- jsimd_idct_islow_neon
- jsimd_idct_4x4_neon
- jsimd_idct_2x2_neon
- jsimd_ycc_\colorid\()_convert_neon* macros
- jsimd_\colorid\()_ycc_convert_neon* macros
- jsimd_fdct_islow_neon
- generate_jsimd_huff_encode_one_block macro

@dcommander, I can create a pull request tomorrow correcting all of those (with functional testing only on emulated environment, no performance benchmarking). Just tell me how you wan't to proceed.

**Comment by dcommander** [comment]
If you can confirm that it fixes the Xvnc crash, then yes-- please create a pull request.  I'm in the process of regression testing the performance of 1.5.1 anyhow, for other reasons, so I can just add this to the tests.

**Comment by mayeut** [comment]
I confirm it fixes the Xvnc crash.
I will create a PR tomorrow evening (So roughly the same time tomorrow) with all those functions fixed regarding ABI conformance.

**Comment by ssvb** [comment]
I wonder when did it get broken? If I remember correctly, there was nothing like this when Linaro did the armv7 -> aarch64 assembly implementation conversion. Here is what the ``jsimd_idct_4x4_neon``` function looked like : https://github.com/ssvb/libjpeg-turbo-linaro-armv8/commit/76a75ea2d0816276d172b3d0ea2b4f7595bd8448#diff-6a0792c7b3c4bb5d7f5d62034063b559R1197

**Comment by ssvb** [comment]
Looks like this regressed in 3728aa01d8c8ab7b6547023e4c141f10dc7755e7

**Comment by ssvb** [comment]
@mayeut thanks, good job investigating this!

**Comment by dcommander** [comment]
@ssvb, despite having my name on it, that commit was still Linaro's work:

**Comment by dcommander** [comment]
@ssvb, despite having my name on it, that commit came from Linaro:  https://sourceforge.net/p/libjpeg-turbo/patches/54/#3d8c.  I don't have a good enough understanding of ARMv8 assembly to be able to tell why it regressed.  Can you provide more details?

**Comment by ssvb** [comment]
@dcommander Thanks for the link. Yes, now I remember it, the patch and the accompanying explanations looked a bit fishy back then. But it was a little bit awkward situation because nobody other than Linaro had 64-bit ARM hardware at that time, so I understand why this patch got committed.

As for the details, @mayeut already provided the explanations and promised to provide a fix. Basically, it is incorrect to ever store data below the stack pointer on most architectures. Because context switching, exceptions handling, signals handling and other things may potentially corrupt this data under the stack pointer. Either way, it is enough to know that this is forbidden by the ABI.

**Comment by nullr0ute** [comment]
Confirmed this is fixed on Fedora 25. Thanks!
